// FineInvoice entitlement gate v2
(() => {
  'use strict';
  const invNo=()=>{const m=String(document.getElementById('invNumber')?.value||'').match(/(?:INV[-_ ]?)(\d+)/i);return m?Number(m[1]):null};
  const freeInvoice=()=>{const n=invNo();return Number.isFinite(n)&&n>=1&&n<=4};
  const invoiceId=()=>typeof currentDraftId!=='undefined'&&currentDraftId!=null?String(currentDraftId):String(new URLSearchParams(location.search).get('invoice')||document.getElementById('invNumber')?.value||'draft');
  const unlocked=(u,id)=>freeInvoice()||String(u?.plan||'').toLowerCase()==='lifetime'||(u?.unlockedInvoiceIds||[]).map(String).includes(String(id));
  async function user(){const sb=getSupabase();if(!sb)return getCurrentUser?.()||null;let r=await sb.auth.getSession();if(!r.data?.session)r=await sb.auth.refreshSession();const a=r.data?.session?.user;if(!a)return null;const m=a.user_metadata||{},p=getCurrentUser?.()||{},plan=['single','lifetime'].includes(String(m.plan??p.plan??'free').toLowerCase())?String(m.plan??p.plan).toLowerCase():'free',u={...p,id:a.id,email:a.email||p.email||'',name:m.name||p.name||a.email||'User',plan,planVerified:m.planVerified===true,paymentProvider:m.paymentProvider||p.paymentProvider||null,freePdfCredits:Math.max(0,Number(m.freePdfCredits??p.freePdfCredits??0)||0),paidSingleCredits:plan==='single'?Math.max(0,Number(m.paidSingleCredits??p.paidSingleCredits??0)||0):0,unlockedInvoiceIds:Array.isArray(m.unlockedInvoiceIds)?m.unlockedInvoiceIds.map(String):(p.unlockedInvoiceIds||[])};u.singleCredits=u.freePdfCredits+u.paidSingleCredits;saveCurrentUser(u);return u}
  async function consume(u,id){if(unlocked(u,id))return{ok:true};const paid=Math.max(0,Number(u.paidSingleCredits||0));if(paid<=0)return{ok:false,error:'No PDF credits remaining.'};const next=paid-1,ids=[...new Set([...(u.unlockedInvoiceIds||[]).map(String),String(id)])],sb=getSupabase();if(!sb)return{ok:false,error:'Authentication service is unavailable.'};const r=await sb.auth.updateUser({data:{freePdfCredits:Number(u.freePdfCredits||0),paidSingleCredits:next,singleCredits:Number(u.freePdfCredits||0)+next,unlockedInvoiceIds:ids}});if(r.error)return{ok:false,error:r.error.message||'Could not save PDF entitlement.'};u.paidSingleCredits=next;u.singleCredits=Number(u.freePdfCredits||0)+next;u.unlockedInvoiceIds=ids;saveCurrentUser(u);return{ok:true}}
  function install(){
    window.downloadPDF=async()=>{const u=await user();if(!u){showToast('Please sign in again to create a PDF.','error',5000);return}const id=invoiceId(),need=!unlocked(u,id)&&!freeInvoice()&&u.plan!=='lifetime';if(need&&Number(u.paidSingleCredits||0)<=0){showToast('No PDF credits remaining. Please purchase a PDF credit or Lifetime Access.','error',5000);return}try{const paper=document.querySelector('#invoiceDoc .invoice-paper');if(!paper)throw Error('Invoice is empty');const c=await html2canvas(paper,{scale:3,useCORS:true,backgroundColor:'#fff',scrollX:0,scrollY:0}),{jsPDF}=window.jspdf,W=210,M=6,CW=W-M*2,CH=297-M*2,mm=CW/c.width,total=c.height*mm,pages=Math.max(1,Math.ceil(total/CH)),doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});for(let pg=0;pg<pages;pg++){if(pg)doc.addPage('a4','portrait');const sy=Math.floor(pg*CH/mm),sh=Math.min(c.height-sy,Math.ceil(CH/mm)),s=document.createElement('canvas');s.width=c.width;s.height=sh;const x=s.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,s.width,s.height);x.drawImage(c,0,sy,c.width,sh,0,0,c.width,sh);doc.addImage(s.toDataURL('image/jpeg',.96),'JPEG',M,M,CW,sh*mm)}if(need){const q=await consume(u,id);if(!q.ok)throw Error(q.error)}doc.save((document.getElementById('invNumber')?.value||'invoice').replace(/[^a-z0-9._-]/gi,'_')+'.pdf');showToast('PDF downloaded! 🎉','success')}catch(e){console.error(e);showToast(e.message||'PDF generation failed.','error',5000)}};
    window.printInvoice=async()=>{const u=await user();if(!u){showToast('Please sign in again to print.','error',5000);return}const id=invoiceId(),need=!unlocked(u,id)&&!freeInvoice()&&u.plan!=='lifetime';if(need){const q=await consume(u,id);if(!q.ok){showToast(q.error,'error',5000);return}}document.body.classList.add('print-mode');window.print();setTimeout(()=>document.body.classList.remove('print-mode'),800)};
    console.log('[FineInvoice] entitlement gate v2');
  }
  window.addEventListener('load',install,{once:true});
})();
